### ISSUE TITLE
Request: set CSS color-scheme based on selected color scheme

### ISSUE THREAD

**Issue by shemetz** [hipstersmoothie/storybook-dark-mode#293]
It would be great if this addon listened to theme changes (in button click listener or through API), and then added the following line of CSS to the Storybook Docs wrapper (or Root, or Body element):

```css
color-scheme: dark;
```

or `color-scheme: light` if it's light.

Currently there's an easy workaround for this, which I use:

```js
const darkMode = useDarkMode();
useEffect(() => {
    document.getElementsByClassName("sb-show-main")[0].style.colorScheme = darkMode ? "dark" : "light";
}, [darkMode]);
```

By adding this `color-scheme` field to the CSS of the containing element, it allows for all downstream components to rely on `light-dark` in styling.

For example, it enables using this style in components:

```css
p {
  /* dark gray background in dark mode, soft white in light mode */
  background-color: light-dark(#111111, #e3e3e3);
}
```
